# Dockerfile.singleuser
FROM quay.io/jupyter/base-notebook:latest

# 切到 root 安裝系統套件
USER root

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y sudo && \
    rm -rf /var/lib/apt/lists/*

# RUN apt-get update && apt-get install -y sudo && apt-get clean

RUN pip install --no-cache-dir "jupyterhub>=5,<6"

RUN echo "jovyan ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER jovyan

# 給 JupyterHub 用的啟動指令
CMD ["start-singleuser.sh"]
